name = "BIRD"
uuid = "6659f9b8-757c-4deb-bcfa-b06cc33ae190"
authors = ["Gustavo <gustavo.aroeira@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
